# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.9
    - 3.8

# what branches should be evaluated
branches:
    only:
        - main

sudo: true

before_install:
    - sudo apt-get install graphviz

# list of commands to run to setup the environment
install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - pip install -r requirements.txt


# a list of commands to run before the main script
before_script:
    - "flake8 --ignore=E501,E722,W605,F401 mlpipeline_analyzer app tests"

# the actual commands to run
script:
    - coverage run -m unittest discover

# generate a coverage report to send to back to user
after_success:
    - coverage run --source=mlpipeline_analyzer,app,tests -m pytest tests/
    - coverage report
    - coveralls
